:toc: macro
= AutoPatch

Patching tool to assist with exclude maintenance.

toc::[]

= Basic Setup

To use a VM, follow the setup instructions from link:http://bit.ly/v3devs[this workshop]

== Authentication
[source, bash]
----
oc login <openshift-cluster-ip>
oc config view
----

== Create a project
Create a project to house this application:

[source, bash]
----
oc new-project <project-name>
----

Create an application using this repository.

[source, bash]
----
oc new-app openshift/python-33-centos7:latest~https://github.com/hzgraham/patchapp.git
----

Then, check the results:

[source, bash]
----
oc get builds -w
----

= Builds

Docker image builds can be initiated by navigating to the "Builds" tab in the V3 web console. Click on the **Start Build** button for each service.

You can also initiate the builds from the command line:

[source, bash]
----
oc start-build patchapp
----

Watch the progress:

[source, bash]
----
oc get pods -w
----

= Routing

In order to view the patchapp, you'll need to expose your service by setting up a Route.
The optional `--hostname` flag allows you to create a custom route to an existing `service`:

[source, bash]
----
oc expose se/patchapp --hostname=<your-patchapp-hostname>
----

Make sure this route is addressable from wherever you are running your browser (an `/etc/hosts` entry in your client _may_ be required).

Excluding the `--hostname` flag should generate a default route that automatically takes advantage of your cluster's wildcard DNS (if available):

[source, bash]
----
oc expose se/patchapp
----

Now, try listing your existing routes:

[source, bash]
----
oc get route
----

= Local Development

== Pre-Requisutes

* python3
* python3-devel
* python-virtualenv

== Run patchapp locally

The 'run' Makefile target will install application dependencies within a python virtual environment and then run the application.

[source, bash]
----
make run
----

= Cleanup

You can clear out everything in your existing project by running the following:

[source, bash]
----
oc delete all --all
----

TIP: Be careful to verify that you're logged into the correct server and project before running this command!
