PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
INSERT INTO "autopatch_server" VALUES(1,'server021.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(2,'server024.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(3,'server022.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(4,'server023.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(5,'server023.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(6,'server016.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(7,'server016.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(8,'server015.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(9,'server019.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(10,'server014.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(11,'server021.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(12,'server010.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(13,'server012.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(14,'server015.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(15,'server019.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(16,'server020.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(17,'server04.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(18,'server010.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(19,'server011.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(20,'server018.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(21,'server022.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(22,'server021.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(23,'server05.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(24,'server016.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(25,'server022.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(26,'server03.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(27,'server01.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(28,'awesome.server.example.com','badthings haxpax','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(29,'server015.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(30,'server014.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(31,'server04.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(32,'server025.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(33,'server017.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(34,'server01.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(35,'server018.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(36,'server05.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(37,'server011.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(38,'server06.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(39,'server05.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(40,'server023.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(41,'server022.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(42,'server06.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(43,'server022.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(44,'server012.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(45,'server018.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(46,'server011.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(47,'server08.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(48,'server05.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(49,'server019.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(50,'server010.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(51,'server015.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(52,'server024.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(53,'server07.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(54,'server08.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(55,'server014.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(56,'server08.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(57,'server012.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(58,'server013.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(59,'server017.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(60,'server020.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(61,'server017.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(62,'server020.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(63,'server03.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(64,'server023.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(65,'server09.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(66,'server010.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(67,'server011.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(68,'server04.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(69,'server013.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(70,'server03.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(71,'server018.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(72,'server04.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(73,'server023.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(74,'server013.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(75,'server01.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(76,'server02.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(77,'server025.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(78,'server02.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(79,'server08.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(80,'server024.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(81,'server019.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(82,'server014.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(83,'server025.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(84,'server021.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(85,'server019.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(86,'server02.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(87,'server016.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(88,'server017.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(89,'server06.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(90,'server01.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(91,'server012.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(92,'server09.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(93,'server014.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(94,'server018.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(95,'server06.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(96,'server05.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(97,'server09.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(98,'server03.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(99,'server07.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(100,'server08.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(101,'server021.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(102,'server021.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(103,'server013.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(104,'server07.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(105,'server012.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(106,'server01.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(107,'server024.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(108,'server015.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(109,'server06.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(110,'server011.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(111,'server01.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(112,'server016.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(113,'server016.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(114,'server09.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(115,'server04.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(116,'server025.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(117,'server02.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(118,'server02.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(119,'server03.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(120,'server020.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(121,'server010.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(122,'server011.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(123,'server014.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(124,'server08.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(125,'server06.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(126,'server025.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(127,'server024.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(128,'server010.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(129,'server09.stage.example.com','bind* mariadb* 389*','IT','','stage',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(130,'server03.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(131,'server025.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(132,'server017.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(133,'server05.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(134,'server013.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(135,'server015.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(136,'server02.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(137,'server09.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(138,'server013.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(139,'server019.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(140,'server017.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(141,'server07.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(142,'server020.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(143,'server04.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(144,'server07.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(145,'server07.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(146,'server012.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(147,'server023.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(148,'server018.prod.example.com','bind* mariadb* 389*','IT','','prod',0,NULL,NULL,0,0);
INSERT INTO "autopatch_server" VALUES(149,'server020.util.example.com','bind*, mariadb*','IT','','prod',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(150,'server022.dev.example.com','bind*, mariadb*','IT','','dev',0,NULL,NULL,1,0);
INSERT INTO "autopatch_server" VALUES(151,'server024.qa.example.com','bind* mariadb* 389*','IT','','qa',0,NULL,NULL,0,0);
COMMIT;
